### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by Unovamata** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#10]
This issue is exclusively intended for feature suggestions to ensure that extension issues or bugs do not become obscured by potential future user requests. 

Kindly submit your ideas or enhancements in the comments section below this "Feature Suggestions" issue. 

Any issues created elsewhere, apart from this designated section, may be subject to closure as they do not pertain to the system as a whole. We appreciate your cooperation.

Comments marked with the 👍 emoji will be added into the repository's features, while 👎 comments will mean the feature suggested is either not feasible or too complex for the system at hand.

Any comments that possess the 🚀 emoji have already been implemented in the extension.

Thank you, I'm glad you continue to use and enjoy NeoBuyer+.

**Comment by Unovamata** [comment]
Thank you for your cooperation, I will work on these in the next update.

Thank you for your continuous support.

**Comment by Unovamata** [comment]
All features suggested have been either added into the system or considered for implementation. Thank you for your patience.

These new features will release in the next major version of the extension. Thank you for using NeoBuyer+.

**Comment by lobt2** [comment]
Hi, appreciate the awesome work you're doing.
Is there a way to have your purchase history persist between installations of new releases?
If not, I'd like to make it a feature suggestion, thanks.

**Comment by Unovamata** [comment]
> Hi, appreciate the awesome work you're doing. Is there a way to have your purchase history persist between installations of new releases? If not, I'd like to make it a feature suggestion, thanks.

Hi! I am glad you are enjoying the work I am doing! I hope you continue to use NeoBuyer+!

To answer your question, yes! There is a way of having your history persist through installations. You have various options.

• To replace all NeoBuyer+ files in the installation folder. Whenever you download a new version of NeoBuyer+, you can just replace the files inside your extension's containing folder. With that you would keep all the data needed for the purchase history.
• Export your configuration presets. If you go into the Tools > Miscellaneous menu, you would see a "Save & Load Configuration" Menu. From there, you will see a myriad of options to export all the data NeoBuyer+ has. With that, you can load your NeoBuyer+'s data in any version from 0.6v onward!

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/35b9efa4-2a1f-457b-a672-9225a7dad8be)

**Comment by Unovamata** [comment]
So essentially you will be asking for the item database to be updated constantly or add an option to add a new object to the database if it doesn't exists yet, right? Can you explain the concept you have in mind with more specificity? It would help me tons to conceptualize something for the extension!

I'm glad you are enjoying the work I am doing on NeoBuyer+, here's the link if you want to buy me a coffee, thank you very much 😄: https://www.buymeacoffee.com/unovamata

**Comment by Unovamata** [comment]
Do not worry about your English! You did great!

I will come up with a solution for that use-case! Thank you for the wonderful idea and the donation, it is really appreciated! 😄 I will give it extra priority thanks to that, so keep an eye out in the following weeks to see if that implementation is added in the way you wanted. Thank you very much for your support and I hope you continue to use NeoBuyer+. 😃

**Comment by kegilan** [comment]
It’s okay dont need to prioritize it was just a thanks :) You have a good
new year, looking forward to any updates ☺️

**Comment by Unovamata** [comment]
All features suggested have been either added into the system or considered for implementation. Thank you for your patience.

These new features will release in the next major version of the extension. Thank you for using NeoBuyer+.

**Comment by prunedgedev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

xxqq170, @VictorDMoura, @devzld, @d1pakda5, @DarrenKong, @ahwind, @Futureee, @zaczyyang, @WendaJackie, @Herbert77, @zhengqiuwan, @ejacky, @ReavenH, @hchfly, @alps-sun, @AtlasRider, @aoster97, @iazkaban, @conacts, @leeseon

**Comment by ovoshuezidos** [comment]
Hello, Unovata, thank you for your hard work. It's an amazing addon. However, the Database seems to be way outdated (Last Update: August 2023?) and it keeps trying to buy things that aren't worth it. Any chance of updating the database? Or making so that we, the users, can manually keep it updated? Thank you!

**Comment by notellingu** [comment]
Hi Unovamata.

I've noticed in the never version, on the haggle page, the Auto-Enter Offer feature seems to be offering way above the item price. For example:
Chocolate Heart 4650np / Auto-Enter 5443np
Menacing Brew 2500np / Auto-Enter 2773
Negg 11100np / Auto-Enter 14211np

The more expensive the item, the more np it will offer.
Unlike previous version where the difference is only a few hundred np depending on the digit.
Could you fix it or is there a value in the script I can modify to solve this profit loss?

**Comment by Unovamata** [comment]
Hi! Sorry if this has caused an inconvenience for you. Yes, indeed the new haggling algorithm offers more than the shopkeepers ask for as a safety measure to not under haggle and not miss out on any items. 

Though you are right, I forgot to add a curve for the more expensive items, I am very sorry about that. Currently, the new haggling algorithm just does a simple multiplication over the base price to generate the haggle.

Expect an update tomorrow to solve that issue, thank you for your report.

**Comment by bluekazoo555** [comment]
**Feature suggestion: option to pause AutoBuyer for xx minutes every xx minutes**

I think all of the currently configurable options are great in helping cut down on getting RS banned. I think in addition it could be nice to be able to configure a long pause every so often to more closely mimic human behavior (e.g. taking breaks). Like I might set it to pause between 5-10 minutes every 30-45 minutes.

I can't state enough how much I appreciate your continued hard work in maintaining and enhancing NeoBuyer+!

**Comment by Unovamata** [comment]
Hi bluekazoo555! The AutoBuyer already possesses a similar feature, it is called: "Pause Extra Time After Successful Purchase". 

Personally, I have not tested if this feature works as intended, but if you find any problems with it, feel free to create a new issue!

The feature suggested is quite easy to implement, so I may add it in a future update! Thank you very much!

**Comment by neopetsa** [comment]
Option to force reload if the page hasnt loaded for X seconds? Happens a lot these days, when playing legit you're way better off trying to refresh again if it hasnt loaded for like 1-2 seconds.

**Comment by neopetsa** [comment]
Well.. Neopets is lagging every day, it has nothing to do with my or your internet speed. My 'forced reload' suggestion would be nothing more than reloading the page instead of letting it sit there for 10~60seconds without loading lol. this is not a user problem its a neopets problem. 

As for the attic I cant explain it any more precise than that, sorry. English is not your first language I guess

**Comment by neopetsa** [comment]
maybe this can help you understand the attic: https://www.neopets.com/~Ohraelia
As well as my personal timekeeping files
[attic timers.txt](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/files/14191616/attic.timers.txt)

**Comment by notellingu** [comment]
Hey there!
Just reporting a my experience with the latest version.
The function to wait a few seconds after a purchase doesn't work. It will immediately goes to shop front and try to buy something resulting in 'Must wait 5 seconds before making another purchase' page.
The Attic auto-refresh function also don't seem to work anymore. It will just show 'Autobuyer running' and not automatically refresh the page as set in the setting.
This one is minor but the auto-haggle function will offer more NP than necessary even to small priced item like 500np, it will offer 700np+. Kind of losing profit a bit.

I would like to add a suggestion:
Have Attic it's own auto-purchase list instead of sharing with main auto-buyer.
Have an auto-buyer for Igloo Garage too

Anyway I love this tool and looking forward to see what upcoming update you're cooking!

**Comment by Unovamata** [comment]
Hi notellingu! Thank you for enjoying NeoBuyer+, it is truly appreciated! Remember to star the project if you see value in it, that would help me a lot. 😄 

Please remember to separate issues from suggestions for better organization.

Some of the reported bugs are fixed. For others, I've implemented measures to prevent them. In the next update, the GUI will display haggle-affecting values, while I suggest keeping the default ones, you can change them to your AutoBuying style.

As for the AutoAttic list suggestion, I do not see this feature as necessary as the size of lists do not actively affect the speed or performance of the AutoBuyer processes. However, if you have a strong reason why it is critical, I am open to considering it for implementation.



All features suggested have been either added into the system or considered for implementation. Thank you for your patience.

These new features will release in the next major version of the extension (0.8v). Thank you for using NeoBuyer+.

**Comment by nslepak** [comment]
hi :) i've been using the autobuyer for a couple days now and i have some suggestions. but first, i'd like to thank you for making this tool and making it available for free! very kind of you. ok, onto the suggestions:

it really took me a while to figure out how to actually use the autobuyer. the FAQs don't really give a detailed how to. here's how i think it works, or at least this is the only way i've been able to get to autobuyer to work: i set all the settings to my preference and then i open a shop in a new tab. then i press enable, go over to the shop tab and refresh once. this seems to then trigger it to start working.

however, i haven't gotten the attic autobuyer or the autopricer to work. i tried the same new tab and refresh to get it started method but it didn't do anything with the autobuyer. and the autopricer, it opens the shop wizard but then it just stalls and does nothing while claiming that it's looking up the price of the first item. i feel like its not that these features don't work but rather that i just dont know how to use it properly.

all that is to say: suggestion #1 would be a thorough manual or tutorial on how to actually use these awesome tools! 

back to the autobuyer - my other suggestion is that you could add an option that if there are many items of something stocked, to limit purchases to just 1 or 2 or whatever number. the reason for this is because it just started buying a bunch of mac n cheese's (i guess because its not in the item database its going off of) and would've continued buying all 13 that were stocked unless i quickly added it to the blacklist. i think its safe to say that rare, high profit items are usually only going to be stocked 1 at a time or 2 tops. i understand that you are working on getting the item database to update in real time, but in the meantime, this duplicate buying limit seems like a simpler workaround for not accidentally buying cheap low profit items.

btw, i think the blacklist was a great idea and i think your UI is great too :)

**Comment by Unovamata** [comment]
Hi nslepak! Thank you for using NeoBuyer+! It really means a lot to me seeing people enjoying my work as a programmer!

First of all, I would like to apologize for all the problems caused thus far because of the extension. NeoBuyer+ is still a WIP, so there would be many areas of improvement before we arrive to version 1.0, but I am continuously improving the extension in any way possible, so thank you for your patience.

Thank you for your suggestions! I specifically liked the user manual one! I may be able to work on that suggestion on the current version of the extension! As for the purchase limits, I can do that in the next version of the extension as it is not a critical feature at the time being. 

The issues you have reported are related to how obsolete the database entries are. The database hasn't been updated since August 2023, so the next version of the extension will make it so the database is updated constantly! I suggest you use a restock list for that matter, you have a Restock List Generator for that case-use while I work on version 0.8!

Once again, thank you very much for your support and interest on NeoBuyer+! I hope you continue to use NeoBuyer+ in the foreseeable future. 😄

**Comment by nslepak** [comment]
Hello again :) Thanks for your comments in response to my last suggestions. After this new update, I have a new one. A warning that we will lose our restock list when we update to the latest version! I didn't realize that would happen, though I now see how that was a big oversight by me, and I lost the restock list I've been working so hard on. Of course, building on that, it'd be great to carry it over automatically.. but I realize that with you working on a real time auto-updating list that this is probably not the best use of your time. But a simple warning to the naive people like me that didn't consider that works just as well :)

Also, I know I suggested a user manual and you liked that idea and will implement that in the next major update. But in the meantime, do you have some short instructions you could give me on how to work the autopricer and auto kitchen quest completer? Would be much appreciated! 

Thanks again for your hard work on this :)

**Comment by Unovamata** [comment]
Hi nslepak! Thank you for your suggestions, I really appreciate them! I would like to address the update issue you are facing. You can read more about what happened here: https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/issues/10#issuecomment-1792955325.

I can add a "How to update the extension" section in the manual in the future, as this seems to be a general problem across the board for many users. In the comment above, you can find ways of circumventing this issue, but NeoBuyer+ already counts with the tools necessary to evade this scenario.

All features suggested have been either added into the system or considered for implementation. Thank you for your patience.

These new features will release in the next major version of the extension (0.8v). Thank you for using NeoBuyer+.

**Comment by neopetsa** [comment]
Going to list the suggestions I made that we spoke about on discord so that its easier for you to keep track of everything (as you asked)

- A way to deal with 'pet lag' in main shops. Which is apparently a deliberate anticheating effort by TNT that prevents people from buying items too quickly by forcing lag on the captcha page. Which would be some way of resubmitting the captcha request every X-XXX MS (set by the user themselves) instead of letting it go through the lag.

- 1 second less refreshing phase per 7 minutes in attic. on the end of the phase, so instead of +4 every 7minutes, +3 every 7 minutes. Which should still be able to catch all restocks just fine but with a few less refreshes so its safer/cleaner. The first phase meaning 14minutes should probably stay the same.

- A rework of how attic handles missing an item. Currently when it misses an item it will pause the buyer which is good but it doesnt consider that there may be a 2nd item to try for after missing the first one. Correct order of operation would be something like : 
Attempt item -> Miss item -> Check for other items to buy -> Pause. 
instead of Attempt -> Miss -> Pause -> Check for other items to buy (which is what it does currently)

Thanks for the effort as always man. Ask me on discord if something was unclear.

**Comment by nslepak** [comment]
hi :) i have another suggestion. a feature that'd be useful would be to be able to specify "go for 2nd best item" for certain shops and not others. some shops on my list are very competitive, so i toggle 2nd best for those and some shops are less competitive so i don't need it. currently i'm switching it manually but would be awesome to be able to set it for a sublist of shops and leave it!

**Comment by Kakashixy** [comment]
Hello! Not sure if I'm missing any configs, but would be nice if the autobuyer returns to the shop's main page after purchasing an item instead of having to manually click on the shopkeeper. :)

Thank you for this awesome program.

**Comment by Kakashixy** [comment]
Hello! Would like to suggest having a config option to move the purchased items to SDB/Shop. :)
Thank you for the awesome program.

**Comment by Unovamata** [comment]
All features suggested have been either added into the system or considered for implementation. Thank you for your patience.

These new features will release in the next major version of the extension (0.8v). Thank you for using NeoBuyer+.

**Comment by WantToMakeNps** [comment]
Suggestion : 

Could you add the feature for rubbish dump.
Getting avatar items is super difficult and having ab similar to main shop buying would be super useful ^^

**Comment by Gursharn007** [comment]
Refresh Shop Only When Cleared: The tooltop says it will not refresh or move to other shops when shop is stocked. 

but how does it detect if a shop has cleared without refreshing?

**Comment by Unovamata** [comment]
All features suggested have been considered for implementation on version 0.8v and beyong. 

Thank you for your continued interest in the improvement and growth of NeoBuyer+.

Please stay tuned for updates in development in the future.

**Comment by Unovamata** [comment]
> Refresh Shop Only When Cleared: The tooltop says it will not refresh or move to other shops when shop is stocked.
> 
> but how does it detect if a shop has cleared without refreshing?

Hi Gursharn007, thank you for your suggestion. In the final 0.7 version this explanation has been solved. Please check the explanation of this setting in the [AutoBuyer Manual Page](https://github.com/Unovamata/AutoBuyerPlus/wiki/AutoBuyer). This User Manual will release along with the final 0.7 version but you can browse it as needed.

**Comment by Kakashixy** [comment]
Hello! Not sure if this is the right place to post, but I kept encountering this error for the past few days even though it is the latest version.

stack:TypeError: Failed to fetch at FetchLatestGitHubVersion (chrome-extension://fkpelamfojecfepefbdpkalokicmnecm/src/bg/background.js:187:36) at CheckVersionWhenBackgroundActive (chrome-extension://fkpelamfojecfepefbdpkalokicmnecm/src/bg/background.js:153:37) at chrome-extension://fkpelamfojecfepefbdpkalokicmnecm/src/bg/background.js:265:1:get=function () { [native code] },set=function () { [native code] },enumerable=false,configurable=true,message:Failed to fetch:value=Failed to fetch,writable=true,enumerable=false,configurable=true,

**Comment by Unovamata** [comment]
Hi Kakashixy, please refer and subscribe to this issue for further resolution of your issue.

**Comment by Unovamata** [comment]
This thread will no longer be updated as it's from a deprecated version of the extension. Thank you everyone for your support on NeoBuyer+.

Please refer to the [AutoBuyer+](https://github.com/Unovamata/AutoBuyerPlus) repository for future updates. 😄
