### ISSUE TITLE
"ExtPay" & "bannerDisplayed" are not Defined

### ISSUE THREAD

**Issue by MacFried** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#13]
Am I doing something wrong, it seems to not be starting on its own.

**Comment by Unovamata** [comment]
Can you be more specific about your problem? 

What is not starting? The AutoBuyer? The AutoPricer? The Attic AutoBuyer? 

I'll close this issue as there are no mentioned or found errors in the extension.

If you need help or find an error after this post, please comment down below.

Thanks!

**Comment by MacFried** [comment]
I have the extension installed into chrome. I have it enabled, and nothing seems to happen. Neither with the AutoBuyer nor AutoAttic. The AutoPricer works, but it seems I cannot get the AutoBuyer too. Perhaps there is a setting I am missing that isn't allowing it to run? or am I missing something.

**Comment by Unovamata** [comment]
Be sure to go to the AutoBuyer's main page and check if the following setting is active:

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/3af5d341-4898-4130-9284-035ee3a8b5d1)

If that doesn't activates the AutoBuyer do the following set of actions inside a main shop:
• Right-click anywhere in the page.
• "Inspect Element" or Ctrl+Shift+C.
• At the topmost position of the opened menu, click on the "Console" option.
• Check if there are any red messages that involve "inject.js".

**Comment by MacFried** [comment]
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/120194849/3700518d-3fab-42b1-8a7a-b83af8b8b666)

**Comment by MacFried** [comment]
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/120194849/c4e7e713-542e-4df5-b7fc-506ced68e7f9)

**Comment by MacFried** [comment]
I redownloaded it, and now this is the error I get.
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/120194849/4db79b54-6b35-4c27-bf39-398315f963e4)

**Comment by Unovamata** [comment]
Thank you for your input! This has been fixed in the next to release build, but for the time being there's a workaround for this.

• Go to the NeoBuyer+ extension configuration page.
• Go to the "AutoBuyer" page.
• Scroll down until you find the option called: "Show Status Banner".
• Deactivate it. Make sure it looks like the image below.

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/a9546e03-97b9-4b43-9b6d-bd02255704e8)

As for the second error, that's a critical error from my part. I'm very sorry about it, I forgot to remove that snippet of code, I'll create a new release addressing this bug fix.

Thank you for your support, let me know if after the update, this problem has been solved.

**Comment by MacFried** [comment]
I have updated the AutoBuyer in chrome. There is no errors in the console, but the extension is still doing nothing when I am on a shop page.

**Comment by MacFried** [comment]
Another error as I let it run for a bit.

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/120194849/2e5d91e9-9cd4-4a7a-b529-d468e821d619)

**Comment by Unovamata** [comment]
You seem to be running the repository's code instead of the [0.53.9v release](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.53.9v).

The exceptions thrown are happening because you're running an untested / not ready for release version of the extension. 
This version of the extension possesses experimental features and most of the time these require constant testing until they reach a releaseable state.

Remember to **always** install and use the [latest released version from the releases link](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.53.9v) and not the code from the repository.

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/6dc86a7e-4cdc-4117-a487-c3cbd4153ed8)
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/b8a08b08-8256-499c-ac24-e7c5e3f89356)

Still, if you install the [0.53.9v release] and Merifoods is still giving you trouble, feel free to reopen this issue as I don't usually frequent that store.

Thank you for your input and support.
