### ISSUE TITLE
Not refreshing on stocked page

### ISSUE THREAD

**Issue by ozloglorious** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#17]
checked all the settings and have done multiple reinstallations, it auto refreshes on an unstocked page but for some reason when it is stocked, it stops.

Timer for refresh does show at the top, and autobuyer is ticked in the on position.

**Comment by ozloglorious** [comment]
Issue appears when shop list is brought down to a single shop

**Comment by ozloglorious** [comment]
I was able to get it to reload the singles shop in question by placing it in the shop list twice
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/149026212/20a270ba-ba45-4e78-a50c-9e684bc9567b)

**Comment by Unovamata** [comment]
It seems this is an old version of the script that will not receive support anymore.

Yes, this problem appeared after the inclusion of quests, this will be fixed in version 0.6v releasing today, so that issue has been already fixed.

But, if the problem still appears, please feel free to reopen the issue once again.

Thank you for your help!
