### ISSUE TITLE
Inefficient haggling?

### ISSUE THREAD

**Issue by lecanardcolvert** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#19]
Hello!

If I remember correctly, only one correct round of haggling was enough to buy an item before a recent update?
Now, the haggling phase isn't as good as before. Sometimes, it takes 5-6 rounds of haggling before the item is bought.
That's strange because a good price is automatically entered, sometimes higher than the asked price.

Is that normal or a bug?

**Comment by Unovamata** [comment]
Are you getting the: "Incorrect click on pet" error?

I may need you to describe that scenario with a bit more specificity. What are you seeing in the window? Does the captcha fails?

The old code did that, the current one tends to be more consistent, as the original did not clicked the pet as consistently as the current version does. But I'm open to read more on this issue.

**Comment by Unovamata** [comment]
So let me see if I understand this.

The haggle value is being set as 0? Is that the issue you're reporting? Because if that is the case I thought I had already fixed that issue. 

Still, in the "Your Offer" input field, does the bot inputs a 0 or does it input the actual price to pay to buy the item?

To summarize, the program is inputting the correct haggle amount in the input box, but not actually sending it in the post request. Correct?

**Comment by Unovamata** [comment]
Another user mentioned the issue, so I will try to dissect what is happening in the code. If you could provide another account on how to reproduce the error it would be a great help.

https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/issues/1#issuecomment-1784078389

**Comment by Unovamata** [comment]
I'll look into it, thank for your patience!

**Comment by Unovamata** [comment]
It seems now it has been fixed!

I am very sorry about the inconvenience caused, the price input and the captcha solving code ran exactly at the same time. So, sometimes the haggle was never inputted.

Thank you reporting the error.

I hope you continue to use NeoBuyer+, I am terribly sorry for any inconvenience.
Thank you for your continuous support.
