### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ezrarising** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#22]
Error message when importing new version into chrome extension:
Could not load javascript 'src/SDBPricer.js' for content script.

**Comment by Unovamata** [comment]
Oh my! That shouldn't be there. Be sure to download the [latest version of NeoBuyer+.](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.63.11v)

I have removed a dependency another developer was not happy with, so that's why you're seeing this error. Can you confirm me if downloading version 0.63.11v fixes the problem you have?

**Comment by Unovamata** [comment]
Since no response was given and the error has been fixed in the newest version of NeoBuyer+ the issue will be closed.

Thank you for your contribution. 😄
