### ISSUE TITLE
How do I know if it's working?

### ISSUE THREAD

**Issue by quintoorschot** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#25]
The banner shows in the shop, but the page does not refresh as regularly as I expected it to.

**Comment by Unovamata** [comment]
Usually this happens because the times set by the user are set too high, you generally have to lower them down in order to see the auto buyer work.

Can you send me a screenshot of the banner? Thank you very much!

**Comment by quintoorschot** [comment]
Problem is resolved. Resetting to default settings did the trick

**Comment by quintoorschot** [comment]
What I don't get however, is why the extension decided to buy the 'how to learn braille' book from the book store with 1000NP loss when the default settings clearly state `Minimum Profit to Click Item = 10000` and `Minimum Profit Percentage to Click Item = 0.5`

**Comment by Unovamata** [comment]
Since you are buying items based on database estimates, the extension may not be updated with the most competitive prices in the game. So that is a caveat of using the database for Auto-Buying I will work on a fix later on to have the most updated prices often, thank you so much for your support and I hope you continue to use NeoBuyer+.
