### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by calderious** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#26]
Error
Could not load javascript 'src/SDBPricer.js' for content script.
Could not load manifest.

Any advice appreciated

**Comment by Unovamata** [comment]
It seems you are downloading the source code of the extension and not the [release .rar file](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/download/0.65.13v/NeoBuyer.0.65.13.rar). Be sure to redownload the correct file in order to install NeoBuyer+.

I will update this release in the near future, thank you very much for your help. :)
