### ISSUE TITLE
stuck on haggle screen

### ISSUE THREAD

**Issue by smcalwem** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#27]
After finishing a purchase and not setting the url to cycle (doing simultaneous windows refreshes), the AB gets stuck on the haggle url forever.

Items also aren't showing up on the history tab.

An aside, if you could add putting items in safety deposit so bags don't get full that would be greatly appreciated.

**Comment by Unovamata** [comment]
Thank you for your report, this has been fixed in the next version of the extension (0.7.4.2) along with some improvements. 

This happened because the original project's foundation used a library called EmailJS, since most users did not used this feature, it has been deprecated, so this error will not appear ever again in future releases of the project. 

Thank you very much for your support. I hope you continue to use NeoBuyer+ for the foreseeable future.
