### ISSUE TITLE
AutoPricer "Player in Quest" Bug

### ISSUE THREAD

**Issue by ovoshuezidos** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#29]
Hello again, Unovata. Thank you for always listening to our suggestions!
I've noticed that there seems to be a bug where the AB keeps buying things for way too much more than the item actual value is (for ex, it tried to buy a Yurble Marking for 60k, when it's actual restock price is 4k). It says on the latest build that this was a problem fixed, but it seems it's still happening.
There's also a little warning popping up when trying to use the AutoPricer, saying my account has a faerie quest when it doesn't.

**Comment by Unovamata** [comment]
Thank you for your report! Yes, this issue has been fixed in version 0.7.7.6. Thanks to a change regarding the random generation of numbers, the haggle generation algorithm created unexpectedly high haggles. This has been fixed thankfully, thank you for your report on the haggling system and I am very sorry for this problem, NeoBuyer+ is a WIP so issues may arise at times.

As for the bug in the AutoPricer, I have not yet experienced that issue myself but I think I know what is causing the issue. Can you offer me more information about this bug? Does it appear all the time or just sometimes?

**Comment by ovoshuezidos** [comment]
Hi, I think I discovered what was causing it! It seems I had the Auto Kitchen Solver set as "active" without knowing, causing the AutoPricer to think I had a faerie quest. Going to the Auto Kitchen page and toggling the "cancel AutoKQ" stopped the AutoPricer pop-up.
Thank you for your hard work, always keeping the program updated. :)

**Comment by Unovamata** [comment]
Thank you for that amazing tip! I thought I had set up that failsafe but it seems I forgot about it!

I will update this issue as soon as possible, thank you for your continuous support!

**Comment by Unovamata** [comment]
This issue has been fixed in version 0.7.7.7. Thank you very much for your report!

If you find the error has not been solved, feel free to reopen this issue once again.

Thank you for your continuous support and I hope you continue to use NeoBuyer+ for the foreseeable future.
