### ISSUE TITLE
A few (small) issues i notice with new version (0.7.17.15)

### ISSUE THREAD

**Issue by neopetsa** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#35]
- The autoattic keeps refreshing through its allocated time frame even after a restock happens. 

- If an item was bought, attempted, or missed, the AutoAttic system will add it multiple times to the extension's purchase History by mistake if its refreshed during or after the purchase process.

- Autoattic possible restock time generation can break, as we discussed, I'm not 100% sure why this happens. It happened to me after clearing all settings and then entering the latest restock time by hand. It fixed itself properly when i made it witness a restock.

- Autoattic restock time can get out of sync likely because of neopets lag (im like 90% sure this is why it happens). It doesnt happen often andagain, its due to the website lag. 
If it tries to refresh but took 20second+ to actually load the page then if a restock happened during that refresh it will mark down the restock time as the time when the page decided to load in. Meaning that the actual restock time could have been anywhere in those 20seconds during which it had trouble loading. Meaning that the restock time will be adjusted possibly inaccurately.
A possible fix for this would be taking note of the time when the refresh was attempted and in case a restock happens there, refer back to the time at which the refresh was attempted, not the time when the page decided to load in.

If its at all confusing what i wrote feel free to ask for clarification on discord ;)
All in all great update and yes im using the attic mostly succesfully, just gotta check every now and then if restock times are still accurate.

**Comment by neopetsa** [comment]
Meaning that the actual restock time could have been anywhere in those 20seconds during which it had trouble loading.

Correction: I suppose the restock happened before you even attempt the refresh in question, not during the lag.

**Comment by Unovamata** [comment]
Thank you for such a detailed report! I am working hard on fixing these problems you have been facing. I will update regularly this issue to let you know the fixes done in real time to the AutoAttic process.

Thank you very much for using NeoBuyer+. I hope you continue to use it for the forseeable future.

**Comment by Unovamata** [comment]
> Autoattic possible restock time generation can break, as we discussed, I'm not 100% sure why this happens. It happened to me after clearing all settings and then entering the latest restock time by hand. It fixed itself properly when i made it witness a restock.

This issue has been fixed now. Thank you for your report. This happened because the next refresh window calculation did not had a failsafe whenever the refreshing wait time was above than 14 minutes (the maximum time to wait for a refresh). This happened because the initial windows were undefined, creating massive wait times for auto refreshing.

**Comment by Unovamata** [comment]
> The autoattic keeps refreshing through its allocated time frame even after a restock happens.

> If an item was bought, attempted, or missed, the AutoAttic system will add it multiple times to the extension's purchase History by mistake if its refreshed during or after the purchase process.

These issues have now been fixed. Since the attic flags were not updated correctly, some logic checks have been added or moved around to fix this problem.

**Comment by Unovamata** [comment]
> Autoattic restock time can get out of sync likely because of neopets lag (im like 90% sure this is why it happens). It doesnt happen often andagain, its due to the website lag.
> If it tries to refresh but took 20second+ to actually load the page then if a restock happened during that refresh it will mark down the restock time as the time when the page decided to load in. Meaning that the actual restock time could have been anywhere in those 20seconds during which it had trouble loading. Meaning that the restock time will be adjusted possibly inaccurately.

Although this is not a system issue in and off itself, this can be fixed by keeping an eye out for the Attics Antics board constantly to validate if the most recent restock time is correct or not.

> A possible fix for this would be taking note of the time when the refresh was attempted and in case a restock happens there, refer back to the time at which the refresh was attempted, not the time when the page decided to load in.

While this solution is solid, this may cause desyncs as well, it may make the AutoAttic process a bit more consistent, yes. Though, what if the attic restocked some seconds after the refresh, of it occurred at the exact moment the page loads? This is why the extension includes a link to navigate to the "Attic Antics" board to get the latest time. In short, desyncs will always happen, it's up to the user to check constantly if their attic times are consistent to the manually reported ones every once in a while.

I will think about this last feature, but for now I will close the issue.
